/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    plugins {
        id("com.google.protobuf") version "0.9.5"
        id("com.google.cloud.artifactregistry.gradle-plugin") version "2.2.5"
        id("com.palantir.git-version") version "4.2.0"
        id("com.google.cloud.tools.jib") version "3.5.1"
        id("org.graalvm.buildtools.native") version "0.10.4"
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "candid-java-playground"
include("candid-api-proto", "candid-api-grpc-server", "candid-api-grpc-client", "candid-api-grpc-server-cloud-run", "candid-inference-impl")
